<?php
use Daxdoxsi\Abcphp\Libs\Mem;
$content = Mem::get('viewContent');
$v = Mem::get('viewVars');
?><!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bootstrap Layout</title>
</head>
<body>
<h3>Layout Markup Code</h3>
<hr>
<?=$content?>
</body>
</html>